import Link from "next/link";
import { ArrowUturnLeftIcon } from "@heroicons/react/24/solid";
import "../globals.css";

export const metadata = {
  title: "Sanity + Next.js Tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="flex items-center justify-between p-2 bg-[#101112] border-b border-[#3f434a]">
            <Link
              href="/"
              className="btn !rounded-[4px] !px-3 text-base font-normal flex items-center text-[#2275FB] transition-colors duration-100 ease-in"
            >
              <ArrowUturnLeftIcon className="h-5 w-5 mr-1" />
              Go to Website
            </Link>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
