import "../globals.css";
import Link from "next/link";
import Footer from "./components/Footer";
import { getProjects, getPages } from "@/sanity/sanity-utils";

export const metadata = {
  title: "Sanity + Next.js Tutorial",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const projects = await getProjects();
  const pages = await getPages();

  return (
    <html lang="en">
      <body>
        <header className="bg-base-100">
          <nav className="navbar container">
            <div className="navbar-start">
              <div id="mobile-menu" className="dropdown">
                <label tabIndex={0} className="btn btn-ghost lg:hidden">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h8m-8 6h16"
                    />
                  </svg>
                </label>
                <ul
                  tabIndex={0}
                  className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52 flex-col-reverse"
                >
                  {pages.map((page, index) => {
                    return (
                      <li key={index}>
                        <Link
                          href={`/${page.slug}`}
                          className={
                            page.slug === "contact" ? "hidden" : "block"
                          }
                        >
                          {page.title}
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              </div>
              <Link href="/" className="btn btn-ghost text-xl">
                testProjekt
              </Link>
            </div>
            <div className="navbar-center hidden lg:flex">
              <ul className="menu menu-horizontal px-1 flex-row-reverse">
                {pages.map((page, index) => {
                  return (
                    <li key={index}>
                      <Link
                        href={`/${page.slug}`}
                        className={page.slug === "contact" ? "hidden" : "block"}
                      >
                        {page.title}
                      </Link>
                    </li>
                  );
                })}
              </ul>
            </div>
            <div className="navbar-end">
              <Link href="/contact" className="btn">
                Contact
              </Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
