import "../globals.css";
import Link from "next/link";
import Head from "next/head";
import { getProjects, getPages } from "@/sanity/sanity-utils";

export const metadata = {
  title: "Sanity + Next.js Tutorial",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const projects = await getProjects();
  const pages = await getPages();

  console.log(projects);
  console.log(pages);
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body>
        <header className="container p-10">
          <ul className="flex items-center justify-center gap-8 lg:gap-16">
            <li className="link">
              <Link href="/">Home</Link>
            </li>
            <div className="flex flex-row-reverse gap-8 lg:gap-16 items-center">
              {pages.map((page, index) => {
                return (
                  <li key={index} className="link">
                    <Link href={`/${page.slug}`}>{page.title}</Link>
                  </li>
                );
              })}
            </div>
          </ul>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
